name: 'Compile SCSS to CSS'
description: 'GitHub Action to compile SCSS to CSS with Sass'

inputs:
  source:
    description: 'Relative path to SASS or SCSS file, eg. ./scss/style.scss'
    required: true

  destination:
    description: 'Path compiled CSS should be saved, eg. ./style.css'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
