name: 'Compile Gulp'
description: 'GitHub Action to compile Gulpfile'

inputs:
  source:
    description: 'UNUSED - Relative path to SASS or SCSS file, eg. ./scss/style.scss'
    required: false

  destination:
    description: 'UNUSED - Path compiled CSS should be saved, eg. ./style.css'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
