inputs:
  source:
    description: 'Path to source SCSS file'
    required: true
    default: './scss/style.scss'
  octocat-eye-color:
    description: 'Output path for CSS build'
    required: true
    default: './style.css'